apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      imagePullSecrets:
      - name: nexus3secret
      containers:
      - image: 192.168.20.122:8627/lion-stag/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
